services:
  - type: web
    name: leetcode-tracker
    runtime: node
    plan: free
    env: node
    region: oregon
    buildCommand: |
      npm install --include=dev
      if ! npx --no vite --version > /dev/null 2>&1; then
        echo "⚠️ Vite not found, installing..."
        npm install vite esbuild --save-dev
      fi
      npm run build
      node deploy-simple.cjs
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
